/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUserRequestCustomprofilefieldsInner } from './auth-email-signup-user-request-customprofilefields-inner';


export interface AuthEmailSignupUserRequest { 
    /**
     * Home city of the user
     */
    City?: string;
    /**
     * Home country code
     */
    Country?: string;
    Customprofilefields?: Array<AuthEmailSignupUserRequestCustomprofilefieldsInner>;
    /**
     * A valid and unique email address
     */
    Email: string;
    /**
     * The first name(s) of the user
     */
    Firstname: string;
    /**
     * The family name of the user
     */
    Lastname: string;
    /**
     * Plain text password
     */
    Password: string;
    /**
     * Recaptcha challenge hash
     */
    Recaptchachallengehash?: string;
    /**
     * Recaptcha response
     */
    Recaptcharesponse?: string;
    /**
     * Redirect the user to this site url after confirmation.
     */
    Redirect?: string;
    /**
     * Username
     */
    Username: string;
}

