/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockIomadCompanyAdminGetLicenseInfoRequestCriteriaInner { 
    /**
     * the user column to search, expected keys (value format) are:                                 \"id\" (int) matching user id,                                 \"name\" (string) license name (Note: you can use % for searching but it may be considerably slower!),                                 \"startdate\" (int) license start date in unix time,                                 \"expirydate\" (int) license expiry date in unix time,                                 \"companyid\" (int) license company id,                                 \"parentid\"  (int) license parent id for split licenses,                                 \"program\"  (bool) license is program,                                 \"instant\"  (bool) license is instant,                                 \"type\"  (int) license type (0 = standard, 1 = reusable, 3 = educator),                                 \"reference\" license reference (Note: you can use % for searching but it may be considerably slower!)
     */
    Key?: string;
    /**
     * the value to search
     */
    Value?: string;
}

