/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockIomadCompanyAdminAssignCoursesRequestCoursesInner { 
    /**
     * Course company ID
     */
    Companyid?: number;
    /**
     * Course ID
     */
    Courseid?: number;
    /**
     * Course department ID
     */
    Departmentid?: number;
    /**
     * Is the course licensed
     */
    Licensed?: boolean;
    /**
     * Does the company own the course
     */
    Owned?: boolean;
}

