/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockIomadCompanyAdminGetLicenseFromId200ResponseLicense { 
    /**
     * All licenses allocated
     */
    Allallocated: boolean;
    /**
     * Allocation
     */
    Allocation: number;
    /**
     * Company ID
     */
    Companyid: number;
    /**
     * Expiry date
     */
    Expirydate: number;
    /**
     * License ID
     */
    Id: number;
    /**
     * Instant
     */
    Instant: boolean;
    /**
     * License name
     */
    Name: string;
    /**
     * Parent ID
     */
    Parentid: number;
    /**
     * Program
     */
    Program: boolean;
    /**
     * Reference
     */
    Reference: string;
    /**
     * Start date
     */
    Startdate: number;
    /**
     * License type - 0 = standard, 1 = reusable, 2 = standard educator, 3 = reusable educator
     */
    Type: number;
    /**
     * Used
     */
    Used: number;
    /**
     * Valid length
     */
    Validlength: number;
}

