/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BlockIomadCompanyAdminGetCompanyCourses200ResponseCompaniesInnerCoursesInner } from './block-iomad-company-admin-get-company-courses-200-response-companies-inner-courses-inner';


export interface BlockIomadCompanyAdminGetCompanyCourses200ResponseCompaniesInner { 
    /**
     * Company address
     */
    Address?: string;
    /**
     * Company city
     */
    City?: string;
    /**
     * Company code
     */
    Code?: string;
    /**
     * Company country
     */
    Country?: string;
    Courses?: Array<BlockIomadCompanyAdminGetCompanyCourses200ResponseCompaniesInnerCoursesInner>;
    /**
     * Company custom1
     */
    Custom1?: string;
    /**
     * Company custom2
     */
    Custom2?: string;
    /**
     * Company custom3
     */
    Custom3?: string;
    /**
     * Company ID
     */
    Id?: number;
    /**
     * Company name
     */
    Name?: string;
    /**
     * Company postcode
     */
    Postcode?: string;
    /**
     * Company region
     */
    Region?: string;
    /**
     * Company shortname
     */
    Shortname?: string;
}

