/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BlockIomadCompanyAdminEditCompaniesRequestCompaniesInner { 
    /**
     * Company location address
     */
    Address?: string;
    /**
     * User default forum auto-subscribe
     */
    Autosubscribe?: number;
    /**
     * Company location city
     */
    City?: string;
    /**
     * Compay code
     */
    Code?: string;
    /**
     * Company contract is terminated when <> 0
     */
    Companyterminated?: number;
    /**
     * Company location country
     */
    Country?: string;
    /**
     * Company custom 1
     */
    Custom1?: string;
    /**
     * Company custom 2
     */
    Custom2?: string;
    /**
     * Company custom 3
     */
    Custom3?: string;
    /**
     * Company custom css
     */
    Customcss?: string;
    /**
     * Ecommerce is disabled when = 0
     */
    Ecommerce?: number;
    /**
     * Company heading color
     */
    Headingcolor?: string;
    /**
     * Company hostname
     */
    Hostname?: string;
    /**
     * User default text editor
     */
    Htmleditor?: number;
    /**
     * Company id number
     */
    Id?: number;
    /**
     * User default language
     */
    Lang?: string;
    /**
     * Company ink color
     */
    Linkcolor?: string;
    /**
     * User default digest type
     */
    Maildigest?: number;
    /**
     * User default email display
     */
    Maildisplay?: number;
    /**
     * User default email format
     */
    Mailformat?: number;
    /**
     * Company main color
     */
    Maincolor?: string;
    /**
     * Company maximum number of users
     */
    Maxusers?: number;
    /**
     * Company long name
     */
    Name?: string;
    /**
     * ID of parent company
     */
    Parentid?: number;
    /**
     * Company location postcode
     */
    Postcode?: string;
    /**
     * Company location region
     */
    Region?: string;
    /**
     * User default screen reader
     */
    Screenreader?: number;
    /**
     * Compay short name
     */
    Shortname?: string;
    /**
     * Number of seconds after termination date to suspend the company
     */
    Suspendafter?: number;
    /**
     * Company is suspended when <> 0
     */
    Suspended?: number;
    /**
     * Company theme
     */
    Theme?: string;
    /**
     * User default timezone
     */
    Timezone?: string;
    /**
     * User default forum tracking
     */
    Trackforums?: number;
    /**
     * Contract termination date in unix timestamp
     */
    Validto?: number;
}

