/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreReportbuilderRetrieveReport200ResponseDataRowsInner } from './core-reportbuilder-retrieve-report-200-response-data-rows-inner';


export interface CoreReportbuilderRetrieveReport200ResponseData { 
    Headers: Array<object>;
    Rows: Array<CoreReportbuilderRetrieveReport200ResponseDataRowsInner>;
    /**
     * totalrowcount
     */
    Totalrowcount: number;
}

