/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreFilesUploadRequest { 
    /**
     * component
     */
    Component: string;
    /**
     * context id
     */
    Contextid?: number;
    /**
     * The context level to put the file in,                         (block, course, coursecat, system, user, module)
     */
    Contextlevel?: string;
    /**
     * file area
     */
    Filearea: string;
    /**
     * file content
     */
    Filecontent: string;
    /**
     * file name
     */
    Filename: string;
    /**
     * file path
     */
    Filepath: string;
    /**
     * The Instance id of item associated                          with the context level
     */
    Instanceid?: number;
    /**
     * associated id
     */
    Itemid: number;
}

