/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreGradesUpdateGradesRequestItemdetails } from './core-grades-update-grades-request-itemdetails';
import { CoreGradesUpdateGradesRequestGradesInner } from './core-grades-update-grades-request-grades-inner';


export interface CoreGradesUpdateGradesRequest { 
    /**
     * The activity ID
     */
    Activityid: number;
    /**
     * A component, for example mod_forum or mod_quiz
     */
    Component: string;
    /**
     * id of course
     */
    Courseid: number;
    Grades?: Array<CoreGradesUpdateGradesRequestGradesInner>;
    Itemdetails?: CoreGradesUpdateGradesRequestItemdetails;
    /**
     * grade item ID number for modules that have multiple grades. Typically this is 0.
     */
    Itemnumber: number;
    /**
     * The source of the grade update
     */
    Source: string;
}

