/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface CoreFilesGetUnusedDraftItemid200Response { 
    /**
     * File area component.
     */
    Component: string;
    /**
     * File area context.
     */
    Contextid: number;
    /**
     * File area name.
     */
    Filearea: string;
    /**
     * File are item id.
     */
    Itemid: number;
    /**
     * File area user id.
     */
    Userid: number;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

