/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreUpdateInplaceEditable200ResponseEditicon } from './core-update-inplace-editable-200-response-editicon';


export interface CoreUpdateInplaceEditable200Response { 
    /**
     * component responsible for the update
     */
    Component?: string;
    /**
     * display value (may contain link or other html tags)
     */
    Displayvalue: string;
    /**
     * hint for editing element
     */
    Edithint?: string;
    Editicon?: CoreUpdateInplaceEditable200ResponseEditicon;
    /**
     * label for editing element
     */
    Editlabel?: string;
    /**
     * identifier of the updated item
     */
    Itemid?: string;
    /**
     * itemtype
     */
    Itemtype?: string;
    /**
     * Should everything be wrapped in the edit link or link displayed separately
     */
    Linkeverything?: number;
    /**
     * options of the element, format depends on type
     */
    Options?: string;
    /**
     * type of the element (text, toggle, select)
     */
    Type?: string;
    /**
     * value of the item as it is stored
     */
    Value?: string;
}

