/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreCalendarGetCalendarEventsRequestOptions { 
    /**
     * Ignore hidden events or not
     */
    Ignorehidden?: boolean;
    /**
     * Set to true to return site events
     */
    Siteevents?: boolean;
    /**
     * Time to which the events should be returned. We treat 0 and null as no end
     */
    Timeend?: number;
    /**
     * Time from which events should be returned
     */
    Timestart?: number;
    /**
     * Set to true to return current user\'s user events
     */
    Userevents?: boolean;
}

