/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInnerDetails } from './core-completion-get-course-completion-status-200-response-completionstatus-completions-inner-details';


/**
 * Completions
 */
export interface CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInner { 
    /**
     * Completion status (true/false)
     */
    Complete?: boolean;
    Details?: CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInnerDetails;
    /**
     * Completion status (Yes/No) a % or number
     */
    Status?: string;
    /**
     * Timestamp for criteria completetion
     */
    Timecompleted?: number;
    /**
     * Completion criteria Title
     */
    Title?: string;
    /**
     * Completion criteria type
     */
    Type?: number;
}

