/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreMessageGetConversationCounts200ResponseTypes { 
    /**
     * Total number of individual conversations
     */
    _1: number;
    /**
     * Total number of group conversations
     */
    _2: number;
    /**
     * Total number of self conversations
     */
    _3: number;
}

