/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInner } from './core-completion-get-course-completion-status-200-response-completionstatus-completions-inner';


export interface CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatus { 
    /**
     * aggregation method 1 means all, 2 means any
     */
    Aggregation: number;
    /**
     * true if the course is complete, false otherwise
     */
    Completed: boolean;
    Completions: Array<CoreCompletionGetCourseCompletionStatus200ResponseCompletionstatusCompletionsInner>;
}

