/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreTagGetTagindexPerAreaRequestTagindex { 
    /**
     * context id where to search for items
     */
    Ctx?: number;
    /**
     * exlusive mode for this tag area
     */
    Excl?: boolean;
    /**
     * context id where the link was displayed
     */
    From?: number;
    /**
     * tag id
     */
    Id?: number;
    /**
     * page number (0-based)
     */
    Page?: number;
    /**
     * search in the context recursive
     */
    Rec?: number;
    /**
     * tag area id
     */
    Ta?: number;
    /**
     * tag name
     */
    Tag?: string;
    /**
     * tag collection id
     */
    Tc?: number;
}

