/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCourseDuplicateCourseRequestOptionsInner } from './core-course-duplicate-course-request-options-inner';


export interface CoreCourseDuplicateCourseRequest { 
    /**
     * duplicated course category parent
     */
    Categoryid: number;
    /**
     * course to duplicate id
     */
    Courseid: number;
    /**
     * duplicated course full name
     */
    Fullname: string;
    Options?: Array<CoreCourseDuplicateCourseRequestOptionsInner>;
    /**
     * duplicated course short name
     */
    Shortname: string;
    /**
     * duplicated course visible, default to yes
     */
    Visible?: number;
}

