/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Rating
 */
export interface CoreRatingGetItemRatings200ResponseRatingsInner { 
    /**
     * rating id
     */
    Id?: number;
    /**
     * rating on scale
     */
    Rating?: string;
    /**
     * time modified (timestamp)
     */
    Timemodified?: number;
    /**
     * user fullname
     */
    Userfullname?: string;
    /**
     * user id
     */
    Userid?: number;
    /**
     * URL user picture
     */
    Userpictureurl?: string;
}

