/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreCourseSearchCoursesRequest { 
    /**
     * criteria name                                                         (search, modulelist (only admins), blocklist (only admins), tagid)
     */
    Criterianame: string;
    /**
     * criteria value
     */
    Criteriavalue: string;
    /**
     * limit to enrolled courses
     */
    Limittoenrolled?: boolean;
    /**
     * limit to courses where completion is enabled
     */
    Onlywithcompletion?: boolean;
    /**
     * page number (0 based)
     */
    Page?: number;
    /**
     * items per page
     */
    Perpage?: number;
    Requiredcapabilities?: Array<object>;
}

