/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreMessageGetConversation200ResponseMessagesInner } from './core-message-get-conversation-200-response-messages-inner';
import { CoreMessageGetConversation200ResponseMembersInner } from './core-message-get-conversation-200-response-members-inner';


export interface CoreMessageGetConversation200Response { 
    /**
     * If the user can delete messages in the conversation for all users
     */
    Candeletemessagesforallusers?: boolean;
    /**
     * The conversation id
     */
    Id: number;
    /**
     * A link to the conversation picture, if set
     */
    Imageurl?: string;
    /**
     * If the user marked this conversation as a favourite
     */
    Isfavourite: boolean;
    /**
     * If the user muted this conversation
     */
    Ismuted: boolean;
    /**
     * If the user has read all messages in the conversation
     */
    Isread: boolean;
    /**
     * Total number of conversation members
     */
    Membercount: number;
    Members: Array<CoreMessageGetConversation200ResponseMembersInner>;
    Messages: Array<CoreMessageGetConversation200ResponseMessagesInner>;
    /**
     * The conversation name, if set
     */
    Name?: string;
    /**
     * A subtitle for the conversation name, if set
     */
    Subname?: string;
    /**
     * The type of the conversation (1=individual,2=group,3=self)
     */
    Type: number;
    /**
     * The number of unread messages in this conversation
     */
    Unreadcount?: number;
}

