/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreEnrolSearchUsersRequest { 
    /**
     * Context ID
     */
    Contextid?: number;
    /**
     * course id
     */
    Courseid: number;
    /**
     * Page number
     */
    Page: number;
    /**
     * Number per page
     */
    Perpage: number;
    /**
     * query
     */
    Search: string;
    /**
     * find a match anywhere, or only at the beginning
     */
    Searchanywhere: boolean;
}

