/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCompetencyGradeCompetency200ResponseActionuser } from './core-competency-grade-competency-200-response-actionuser';


export interface CoreReportbuilderListReports200ResponseReportsInner { 
    /**
     * area
     */
    Area?: string;
    /**
     * component
     */
    Component?: string;
    /**
     * conditiondata
     */
    Conditiondata?: string;
    /**
     * contextid
     */
    Contextid?: number;
    /**
     * id
     */
    Id?: number;
    /**
     * itemid
     */
    Itemid?: number;
    Modifiedby?: CoreCompetencyGradeCompetency200ResponseActionuser;
    /**
     * name
     */
    Name?: string;
    /**
     * settingsdata
     */
    Settingsdata?: string;
    /**
     * source
     */
    Source?: string;
    /**
     * sourcename
     */
    Sourcename?: string;
    /**
     * timecreated
     */
    Timecreated?: number;
    /**
     * timemodified
     */
    Timemodified?: number;
    /**
     * type
     */
    Type?: number;
    /**
     * uniquerows
     */
    Uniquerows?: boolean;
    /**
     * usercreated
     */
    Usercreated?: number;
    /**
     * usermodified
     */
    Usermodified?: number;
}

