/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreUserSearchIdentity200ResponseListInnerExtrafieldsInner } from './core-user-search-identity-200-response-list-inner-extrafields-inner';


export interface CoreUserSearchIdentity200ResponseListInner { 
    Extrafields?: Array<CoreUserSearchIdentity200ResponseListInnerExtrafieldsInner>;
    /**
     * The fullname of the user
     */
    Fullname?: string;
    /**
     * ID of the user
     */
    Id?: number;
}

