/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreMessageGetConversationMembersRequest { 
    /**
     * The id of the conversation
     */
    Conversationid: number;
    /**
     * Do we want to include contact requests?
     */
    Includecontactrequests?: boolean;
    /**
     * Do we want to include privacy info?
     */
    Includeprivacyinfo?: boolean;
    /**
     * Limit from
     */
    Limitfrom?: number;
    /**
     * Limit number
     */
    Limitnum?: number;
    /**
     * The id of the user we are performing this action on behalf of
     */
    Userid: number;
}

