/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreTagGetTagindex200Response { 
    /**
     * name of anchor
     */
    Anchor?: string;
    /**
     * component
     */
    Component: string;
    /**
     * title
     */
    Content: string;
    /**
     * text for exclusive link
     */
    Exclusivetext?: string;
    /**
     * URL for exclusive link
     */
    Exclusiveurl?: string;
    /**
     * whether the content is present
     */
    Hascontent: number;
    /**
     * itemtype
     */
    Itemtype: string;
    /**
     * URL for the next page
     */
    Nextpageurl?: string;
    /**
     * URL for the next page
     */
    Prevpageurl?: string;
    /**
     * tag area id
     */
    Ta: number;
    /**
     * tag id
     */
    Tagid: number;
    /**
     * title
     */
    Title: string;
}

