/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreCourseImportCourseRequestOptionsInner { 
    /**
     * The backup option name:                                             \"activities\" (int) Include course activites (default to 1 that is equal to yes),                                             \"blocks\" (int) Include course blocks (default to 1 that is equal to yes),                                             \"filters\" (int) Include course filters  (default to 1 that is equal to yes)
     */
    Name?: string;
    /**
     * the value for the option 1 (yes) or 0 (no)
     */
    Value?: string;
}

