/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreReportbuilderColumnsAdd200ResponseSortablecolumnsInner } from './core-reportbuilder-columns-add-200-response-sortablecolumns-inner';


export interface CoreReportbuilderColumnsAdd200Response { 
    /**
     * hassortablecolumns
     */
    Hassortablecolumns: boolean;
    /**
     * helpicon
     */
    Helpicon: string;
    Sortablecolumns: Array<CoreReportbuilderColumnsAdd200ResponseSortablecolumnsInner>;
}

