/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreCompetencyGradeCompetency200ResponseActionuser { 
    /**
     * department
     */
    Department: string;
    /**
     * email
     */
    Email: string;
    /**
     * fullname
     */
    Fullname: string;
    /**
     * id
     */
    Id: number;
    /**
     * identity
     */
    Identity: string;
    /**
     * idnumber
     */
    Idnumber: string;
    /**
     * institution
     */
    Institution: string;
    /**
     * phone1
     */
    Phone1: string;
    /**
     * phone2
     */
    Phone2: string;
    /**
     * profileimageurl
     */
    Profileimageurl: string;
    /**
     * profileimageurlsmall
     */
    Profileimageurlsmall: string;
    /**
     * profileurl
     */
    Profileurl: string;
}

