/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreEnrolUnenrolUserEnrolment200ResponseErrorsInner } from './core-enrol-unenrol-user-enrolment-200-response-errors-inner';


export interface CoreEnrolUnenrolUserEnrolment200Response { 
    Errors: Array<CoreEnrolUnenrolUserEnrolment200ResponseErrorsInner>;
    /**
     * True if the user\'s enrolment was successfully updated
     */
    Result: boolean;
}

