/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreQuestionUpdateFlagRequest { 
    /**
     * computed checksum with the last three arguments and                              the users username
     */
    Checksum: string;
    /**
     * the new state of the flag. true = flagged
     */
    Newstate: boolean;
    /**
     * the question_attempt id
     */
    Qaid: number;
    /**
     * the question usage id.
     */
    Qubaid: number;
    /**
     * the question id
     */
    Questionid: number;
    /**
     * the slot number within the usage
     */
    Slot: number;
}

