/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreTagUpdateTagsRequestTagsInner { 
    /**
     * tag description
     */
    Description?: string;
    /**
     * tag description format
     */
    Descriptionformat?: number;
    /**
     * flag
     */
    Flag?: number;
    /**
     * tag id
     */
    Id?: number;
    /**
     * whether this flag is standard
     */
    Isstandard?: number;
    /**
     * (deprecated, use isstandard) whether this flag is standard
     */
    Official?: number;
    /**
     * tag raw name (may contain capital letters)
     */
    Rawname?: string;
}

