/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCohortCreateCohortsRequestCohortsInnerCustomfieldsInner } from './core-cohort-create-cohorts-request-cohorts-inner-customfields-inner';
import { CoreCohortCreateCohortsRequestCohortsInnerCategorytype } from './core-cohort-create-cohorts-request-cohorts-inner-categorytype';


export interface CoreCohortCreateCohortsRequestCohortsInner { 
    Categorytype?: CoreCohortCreateCohortsRequestCohortsInnerCategorytype;
    Customfields?: Array<CoreCohortCreateCohortsRequestCohortsInnerCustomfieldsInner>;
    /**
     * cohort description
     */
    Description?: string;
    /**
     * description format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Descriptionformat?: number;
    /**
     * cohort idnumber
     */
    Idnumber?: string;
    /**
     * cohort name
     */
    Name?: string;
    /**
     * the cohort theme. The allowcohortthemes setting must be enabled on Moodle
     */
    Theme?: string;
    /**
     * cohort visible
     */
    Visible?: boolean;
}

