/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreReportbuilderConditionsDelete200ResponseAvailableconditionsInner } from './core-reportbuilder-conditions-delete-200-response-availableconditions-inner';


export interface CoreReportbuilderConditionsDelete200Response { 
    /**
     * activeconditionsform
     */
    Activeconditionsform: string;
    Availableconditions: Array<CoreReportbuilderConditionsDelete200ResponseAvailableconditionsInner>;
    /**
     * hasactiveconditions
     */
    Hasactiveconditions: boolean;
    /**
     * hasavailableconditions
     */
    Hasavailableconditions: boolean;
    /**
     * helpicon
     */
    Helpicon: string;
    /**
     * javascript
     */
    Javascript?: string;
}

