/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreReportbuilderFiltersDelete200Response } from './core-reportbuilder-filters-delete-200-response';
import { CoreReportbuilderReportsGet200ResponseAttributesInner } from './core-reportbuilder-reports-get-200-response-attributes-inner';
import { CoreReportbuilderConditionsDelete200Response } from './core-reportbuilder-conditions-delete-200-response';
import { CoreReportbuilderReportsGet200ResponseSidebarmenucards } from './core-reportbuilder-reports-get-200-response-sidebarmenucards';
import { CoreReportbuilderColumnsDelete200Response } from './core-reportbuilder-columns-delete-200-response';
import { CoreReportbuilderReportsGet200ResponseCardview } from './core-reportbuilder-reports-get-200-response-cardview';


export interface CoreReportbuilderReportsGet200Response { 
    /**
     * area
     */
    Area: string;
    Attributes: Array<CoreReportbuilderReportsGet200ResponseAttributesInner>;
    Cardview?: CoreReportbuilderReportsGet200ResponseCardview;
    /**
     * classes
     */
    Classes: string;
    /**
     * component
     */
    Component: string;
    /**
     * conditiondata
     */
    Conditiondata: string;
    Conditions?: CoreReportbuilderConditionsDelete200Response;
    /**
     * contextid
     */
    Contextid: number;
    /**
     * editmode
     */
    Editmode: boolean;
    Filters?: CoreReportbuilderFiltersDelete200Response;
    /**
     * filtersapplied
     */
    Filtersapplied: number;
    /**
     * filtersform
     */
    Filtersform: string;
    /**
     * filterspresent
     */
    Filterspresent: boolean;
    /**
     * id
     */
    Id: number;
    /**
     * itemid
     */
    Itemid: number;
    /**
     * javascript
     */
    Javascript: string;
    /**
     * name
     */
    Name: string;
    /**
     * settingsdata
     */
    Settingsdata: string;
    Sidebarmenucards?: CoreReportbuilderReportsGet200ResponseSidebarmenucards;
    Sorting?: CoreReportbuilderColumnsDelete200Response;
    /**
     * source
     */
    Source: string;
    /**
     * table
     */
    Table: string;
    /**
     * timecreated
     */
    Timecreated: number;
    /**
     * timemodified
     */
    Timemodified: number;
    /**
     * type
     */
    Type: number;
    /**
     * uniquerows
     */
    Uniquerows: boolean;
    /**
     * usercreated
     */
    Usercreated: number;
    /**
     * usermodified
     */
    Usermodified: number;
}

