/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreGradesGetGradeitems200ResponseGradeItemsInner { 
    /**
     * The grade category of the grade item
     */
    Category?: string;
    /**
     * An ID for the grade item
     */
    Id?: string;
    /**
     * The full name of the grade item
     */
    Itemname?: string;
}

