/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreBlogGetEntries200ResponseEntriesInnerAttachmentfilesInner } from './core-blog-get-entries-200-response-entries-inner-attachmentfiles-inner';
import { CoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner } from './core-blog-get-entries-200-response-entries-inner-summaryfiles-inner';
import { CoreBlogGetEntries200ResponseEntriesInnerTagsInner } from './core-blog-get-entries-200-response-entries-inner-tags-inner';


export interface CoreBlogGetEntries200ResponseEntriesInner { 
    /**
     * Post atachment.
     */
    Attachment?: string;
    Attachmentfiles?: Array<CoreBlogGetEntries200ResponseEntriesInnerAttachmentfilesInner>;
    /**
     * Post content.
     */
    Content?: string;
    /**
     * Course where the post was created.
     */
    Courseid?: number;
    /**
     * Course module id where the post was created.
     */
    Coursemoduleid?: number;
    /**
     * When it was created.
     */
    Created?: number;
    /**
     * Post content format.
     */
    Format?: number;
    /**
     * Group post was created for.
     */
    Groupid?: number;
    /**
     * Post/entry id.
     */
    Id?: number;
    /**
     * When it was last modified.
     */
    Lastmodified?: number;
    /**
     * Where it was published the post (blog, blog_external...).
     */
    Module?: string;
    /**
     * Module id where the post was created (not used anymore).
     */
    Moduleid?: number;
    /**
     * Post publish state.
     */
    Publishstate?: string;
    /**
     * Post rating.
     */
    Rating?: number;
    /**
     * Post subject.
     */
    Subject?: string;
    /**
     * Post summary.
     */
    Summary?: string;
    Summaryfiles?: Array<CoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner>;
    /**
     * summary format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Summaryformat?: number;
    Tags?: Array<CoreBlogGetEntries200ResponseEntriesInnerTagsInner>;
    /**
     * Post unique hash.
     */
    Uniquehash?: string;
    /**
     * Post author.
     */
    Userid?: number;
    /**
     * User that updated the post.
     */
    Usermodified?: number;
}

