/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CoreUserAddUserDeviceRequest { 
    /**
     * the app id, usually something like com.moodle.moodlemobile
     */
    Appid: string;
    /**
     * the device model \'Nexus4\' or \'iPad1,1\' etc.
     */
    Model: string;
    /**
     * the device name, \'occam\' or \'iPhone\' etc.
     */
    Name: string;
    /**
     * the device platform \'iOS\' or \'Android\' etc.
     */
    Platform: string;
    /**
     * the app generated public key
     */
    Publickey?: string;
    /**
     * the device PUSH token/key/identifier/registration id
     */
    Pushid: string;
    /**
     * the device UUID
     */
    Uuid: string;
    /**
     * the device version \'6.1.2\' or \'4.2.2\' etc.
     */
    Version: string;
}

