/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreMessageMessageProcessorConfigFormRequestFormvaluesInner } from './core-message-message-processor-config-form-request-formvalues-inner';


export interface CoreMessageMessageProcessorConfigFormRequest { 
    Formvalues: Array<CoreMessageMessageProcessorConfigFormRequestFormvaluesInner>;
    /**
     * The name of the message processor
     */
    Name: string;
    /**
     * id of the user, 0 for current user
     */
    Userid: number;
}

