/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GradingformGuideGraderGradingpanelFetch200ResponseGradeCriterionInner { 
    /**
     * The description of the criterion
     */
    Description?: string;
    /**
     * The description of the criterion for markers
     */
    Descriptionmarkers?: string;
    /**
     * The id of the criterion
     */
    Id?: number;
    /**
     * The maximum score for this criterion
     */
    Maxscore?: number;
    /**
     * The name of the criterion
     */
    Name?: string;
    /**
     * Any remarks for this criterion for the user being assessed
     */
    Remark?: string;
    /**
     * The current score for user being assessed
     */
    Score?: number;
}

