/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';
import { GradereportSingleviewGetGradeItemsForSearchWidget200ResponseGradeitemsInner } from './gradereport-singleview-get-grade-items-for-search-widget-200-response-gradeitems-inner';


export interface GradereportSingleviewGetGradeItemsForSearchWidget200Response { 
    Gradeitems: Array<GradereportSingleviewGetGradeItemsForSearchWidget200ResponseGradeitemsInner>;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

