/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GradereportUserGetGradeItems200ResponseUsergradesInnerGradeitemsInner } from './gradereport-user-get-grade-items-200-response-usergrades-inner-gradeitems-inner';


export interface GradereportUserGetGradeItems200ResponseUsergradesInner { 
    /**
     * course id
     */
    Courseid?: number;
    /**
     * course idnumber
     */
    Courseidnumber?: string;
    Gradeitems?: Array<GradereportUserGetGradeItems200ResponseUsergradesInnerGradeitemsInner>;
    /**
     * table max depth (needed for printing it)
     */
    Maxdepth?: number;
    /**
     * user fullname
     */
    Userfullname?: string;
    /**
     * user id
     */
    Userid?: number;
    /**
     * user idnumber
     */
    Useridnumber?: string;
}

