/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GradingformRubricGraderGradingpanelStore200ResponseGradeCriteriaInnerLevelsInner } from './gradingform-rubric-grader-gradingpanel-store-200-response-grade-criteria-inner-levels-inner';


export interface GradingformRubricGraderGradingpanelStore200ResponseGradeCriteriaInner { 
    /**
     * Description of the Criteria
     */
    Description?: string;
    /**
     * ID of the Criteria
     */
    Id?: number;
    Levels?: Array<GradingformRubricGraderGradingpanelStore200ResponseGradeCriteriaInnerLevelsInner>;
    /**
     * Any remarks for this criterion for the user being assessed
     */
    Remark?: string;
}

