/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModScormGetScormScoTracks200ResponseDataTracksInner } from './mod-scorm-get-scorm-sco-tracks-200-response-data-tracks-inner';


export interface ModScormGetScormScoTracks200ResponseData { 
    /**
     * Attempt number
     */
    Attempt: number;
    Tracks: Array<ModScormGetScormScoTracks200ResponseDataTracksInner>;
}

