/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModWorkshopGetReviewerAssessments200ResponseAssessmentsInner } from './mod-workshop-get-reviewer-assessments-200-response-assessments-inner';
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface ModWorkshopGetReviewerAssessments200Response { 
    Assessments: Array<ModWorkshopGetReviewerAssessments200ResponseAssessmentsInner>;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

