/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModWikiGetSubwikiFilesRequest { 
    /**
     * Subwiki\'s group ID, -1 means current group. It will be ignored if the wiki doesn\'t use groups.
     */
    Groupid?: number;
    /**
     * Subwiki\'s user ID, 0 means current user. It will be ignored in collaborative wikis.
     */
    Userid?: number;
    /**
     * Wiki instance ID.
     */
    Wikiid: number;
}

