/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface ModForumCanAddDiscussion200Response { 
    /**
     * True if the user can add attachments, false otherwise.
     */
    Cancreateattachment?: boolean;
    /**
     * True if the user can pin discussions, false otherwise.
     */
    Canpindiscussions?: boolean;
    /**
     * True if the user can add discussions, false otherwise.
     */
    Status: boolean;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

