/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';
import { ModLessonGetLessonAccessInformation200ResponsePreventaccessreasonsInner } from './mod-lesson-get-lesson-access-information-200-response-preventaccessreasons-inner';


export interface ModLessonGetLessonAccessInformation200Response { 
    /**
     * The number of attempts done by the user.
     */
    Attemptscount: number;
    /**
     * Whether the user can grade the lesson or not.
     */
    Cangrade: boolean;
    /**
     * Whether the user can manage the lesson or not.
     */
    Canmanage: boolean;
    /**
     * Whether the user can view the lesson reports or not.
     */
    Canviewreports: boolean;
    /**
     * The lesson first page id.
     */
    Firstpageid: number;
    /**
     * The last page seen id.
     */
    Lastpageseen: number;
    /**
     * Whether the user left during a timed session.
     */
    Leftduringtimedsession: boolean;
    Preventaccessreasons: Array<ModLessonGetLessonAccessInformation200ResponsePreventaccessreasonsInner>;
    /**
     * Whether the lesson is in review mode for the current user.
     */
    Reviewmode: boolean;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

