/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModWorkshopGetUserPlan200ResponseUserplanExamplesInner { 
    /**
     * Example submission assessment id.
     */
    Assessmentid?: number;
    /**
     * The submission grade.
     */
    Grade?: number;
    /**
     * The assessment grade.
     */
    Gradinggrade?: number;
    /**
     * Example submission id.
     */
    Id?: number;
    /**
     * Example submission title.
     */
    Title?: string;
}

