/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModAssignGetSubmissionStatus200ResponseFeedbackGrade } from './mod-assign-get-submission-status-200-response-feedback-grade';
import { ModAssignGetSubmissionStatus200ResponseFeedbackPluginsInner } from './mod-assign-get-submission-status-200-response-feedback-plugins-inner';


export interface ModAssignGetSubmissionStatus200ResponseFeedback { 
    Grade?: ModAssignGetSubmissionStatus200ResponseFeedbackGrade;
    /**
     * The date the user was graded.
     */
    Gradeddate: number;
    /**
     * Grade rendered into a format suitable for display.
     */
    Gradefordisplay: string;
    Plugins?: Array<ModAssignGetSubmissionStatus200ResponseFeedbackPluginsInner>;
}

