/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModQuizGetCombinedReviewOptions200ResponseSomeoptionsInner } from './mod-quiz-get-combined-review-options-200-response-someoptions-inner';
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';
import { ModQuizGetCombinedReviewOptions200ResponseAlloptionsInner } from './mod-quiz-get-combined-review-options-200-response-alloptions-inner';


export interface ModQuizGetCombinedReviewOptions200Response { 
    Alloptions: Array<ModQuizGetCombinedReviewOptions200ResponseAlloptionsInner>;
    Someoptions: Array<ModQuizGetCombinedReviewOptions200ResponseSomeoptionsInner>;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

