/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModH5pactivityGetUserAttempts200ResponseUsersattemptsInnerScored } from './mod-h5pactivity-get-user-attempts-200-response-usersattempts-inner-scored';
import { ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner } from './mod-h5pactivity-get-attempts-200-response-usersattempts-inner-scored-attempts-inner';


export interface ModH5pactivityGetUserAttempts200ResponseUsersattemptsInner { 
    Attempts?: Array<ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner>;
    Scored?: ModH5pactivityGetUserAttempts200ResponseUsersattemptsInnerScored;
    /**
     * The user id
     */
    Userid?: number;
}

