/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModAssignSaveGradesRequestGradesInnerPlugindata } from './mod-assign-save-grades-request-grades-inner-plugindata';
import { ModAssignSaveGradeRequestAdvancedgradingdata } from './mod-assign-save-grade-request-advancedgradingdata';


export interface ModAssignSaveGradesRequestGradesInner { 
    /**
     * Allow another attempt if manual attempt reopen method
     */
    Addattempt?: boolean;
    Advancedgradingdata?: ModAssignSaveGradeRequestAdvancedgradingdata;
    /**
     * The attempt number (-1 means latest attempt)
     */
    Attemptnumber?: number;
    /**
     * The new grade for this user. Ignored if advanced grading used
     */
    Grade?: number;
    Plugindata?: ModAssignSaveGradesRequestGradesInnerPlugindata;
    /**
     * The student id to operate on
     */
    Userid?: number;
    /**
     * The next marking workflow state
     */
    Workflowstate?: string;
}

