/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner } from './core-block-get-dashboard-blocks-200-response-blocks-inner-contents-files-inner';


export interface ModResourceGetResourcesByCourses200ResponseResourcesInner { 
    Contentfiles?: Array<CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>;
    /**
     * Course id
     */
    Course?: number;
    /**
     * Course module id
     */
    Coursemodule?: number;
    /**
     * How to display the resource
     */
    Display?: number;
    /**
     * Display options (width, height)
     */
    Displayoptions?: string;
    /**
     * If filters should be applied to the resource content
     */
    Filterfiles?: number;
    /**
     * Group id
     */
    Groupingid?: number;
    /**
     * Group mode
     */
    Groupmode?: number;
    /**
     * Activity instance id
     */
    Id?: number;
    /**
     * Activity introduction
     */
    Intro?: string;
    Introfiles?: Array<CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>;
    /**
     * intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Introformat?: number;
    /**
     * Forced activity language
     */
    Lang?: string;
    /**
     * Legacy files flag
     */
    Legacyfiles?: number;
    /**
     * Legacy files last control flag
     */
    Legacyfileslast?: number;
    /**
     * Activity name
     */
    Name?: string;
    /**
     * Incremented when after each file changes, to avoid cache
     */
    Revision?: number;
    /**
     * Course section id
     */
    Section?: number;
    /**
     * Last time the resource was modified
     */
    Timemodified?: number;
    /**
     * Whether this resource was migrated
     */
    Tobemigrated?: number;
    /**
     * Visible
     */
    Visible?: boolean;
}

