/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModWorkshopGetGradesReport200ResponseReportGradesInnerReviewerofInner { 
    /**
     * The id of the assessment.
     */
    Assessmentid?: number;
    /**
     * The grade for submission.
     */
    Grade?: number;
    /**
     * The grade for assessment.
     */
    Gradinggrade?: number;
    /**
     * The aggregated grade overrided.
     */
    Gradinggradeover?: number;
    /**
     * The id of the submission assessed.
     */
    Submissionid?: number;
    /**
     * The id of the user (0 when is configured to do not display names).
     */
    Userid?: number;
    /**
     * The weight of the assessment for aggregation.
     */
    Weight?: number;
}

