/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModLtiCreateToolType200ResponseUrls } from './mod-lti-create-tool-type-200-response-urls';
import { ModLtiCreateToolType200ResponseState } from './mod-lti-create-tool-type-200-response-state';


export interface ModLtiCreateToolType200Response { 
    Capabilitygroups?: Array<object>;
    /**
     * Client ID
     */
    Clientid: string;
    /**
     * Tool type course
     */
    Courseid?: number;
    /**
     * Deployment ID
     */
    Deploymentid: number;
    /**
     * Tool type description
     */
    Description: string;
    /**
     * Indicate if capabilitygroups is populated
     */
    Hascapabilitygroups: boolean;
    /**
     * Tool type id
     */
    Id: number;
    /**
     * The number of times this tool is being used
     */
    Instancecount: number;
    Instanceids?: Array<object>;
    /**
     * Tool type name
     */
    Name: string;
    /**
     * Platform ID
     */
    Platformid: string;
    State: ModLtiCreateToolType200ResponseState;
    Urls: ModLtiCreateToolType200ResponseUrls;
}

