/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModDataGetEntry200ResponseRatinginfoScalesInner } from './mod-data-get-entry-200-response-ratinginfo-scales-inner';
import { ModDataGetEntry200ResponseRatinginfoRatingsInner } from './mod-data-get-entry-200-response-ratinginfo-ratings-inner';


export interface ModDataGetEntry200ResponseRatinginfo { 
    /**
     * Whether the user can view all the individual ratings.
     */
    Canviewall?: boolean;
    /**
     * Whether the user can view aggregate of ratings of others.
     */
    Canviewany?: boolean;
    /**
     * Context name.
     */
    Component: string;
    /**
     * Context id.
     */
    Contextid: number;
    /**
     * Rating area name.
     */
    Ratingarea: string;
    Ratings?: Array<ModDataGetEntry200ResponseRatinginfoRatingsInner>;
    Scales?: Array<ModDataGetEntry200ResponseRatinginfoScalesInner>;
}

