/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * grade information
 */
export interface ModAssignGetGrades200ResponseAssignmentsInnerGradesInner { 
    /**
     * assignment id
     */
    Assignment?: number;
    /**
     * attempt number
     */
    Attemptnumber?: number;
    /**
     * grade
     */
    Grade?: string;
    /**
     * grade rendered into a format suitable for display
     */
    Gradefordisplay?: string;
    /**
     * grader, -1 if grader is hidden
     */
    Grader?: number;
    /**
     * grade id
     */
    Id?: number;
    /**
     * grade creation time
     */
    Timecreated?: number;
    /**
     * grade last modified time
     */
    Timemodified?: number;
    /**
     * student id
     */
    Userid?: number;
}

