/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModScormGetScormScoes200ResponseScoesInnerExtradataInner } from './mod-scorm-get-scorm-scoes-200-response-scoes-inner-extradata-inner';


/**
 * SCORM SCO data
 */
export interface ModScormGetScormScoes200ResponseScoesInner { 
    Extradata?: Array<ModScormGetScormScoes200ResponseScoesInnerExtradataInner>;
    /**
     * sco id
     */
    Id?: number;
    /**
     * identifier
     */
    Identifier?: string;
    /**
     * launch file
     */
    Launch?: string;
    /**
     * manifest id
     */
    Manifest?: string;
    /**
     * organization id
     */
    Organization?: string;
    /**
     * parent
     */
    Parent?: string;
    /**
     * scorm id
     */
    Scorm?: number;
    /**
     * scorm type (asset, sco)
     */
    Scormtype?: string;
    /**
     * sort order
     */
    Sortorder?: number;
    /**
     * sco title
     */
    Title?: string;
}

