/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModAssignSaveGradeRequestPlugindataAssignfeedbackcommentsEditor } from './mod-assign-save-grade-request-plugindata-assignfeedbackcomments-editor';


export interface ModAssignSaveGradeRequestPlugindata { 
    AssignfeedbackcommentsEditor?: ModAssignSaveGradeRequestPlugindataAssignfeedbackcommentsEditor;
    /**
     * The id of a draft area containing files for this feedback.
     */
    FilesFilemanager?: number;
}

