/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';
import { ModBigbluebuttonbnGetRecordingsToImport200ResponseTabledata } from './mod-bigbluebuttonbn-get-recordings-to-import-200-response-tabledata';


export interface ModBigbluebuttonbnGetRecordingsToImport200Response { 
    /**
     * Whether the fetch was successful
     */
    Status: boolean;
    Tabledata?: ModBigbluebuttonbnGetRecordingsToImport200ResponseTabledata;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

