/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface ModQuizGetAttemptAccessInformation200Response { 
    /**
     * When the attempt must be submitted (determined by rules).
     */
    Endtime?: number;
    /**
     * Whether there is no way the user will ever be allowed to attempt.
     */
    Isfinished: boolean;
    /**
     * whether a check is required before the user                                                                     starts/continues his attempt.
     */
    Ispreflightcheckrequired?: boolean;
    Preventnewattemptreasons: Array<object>;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

