/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner } from './mod-h5pactivity-get-attempts-200-response-usersattempts-inner-scored-attempts-inner';


export interface ModH5pactivityGetUserAttempts200ResponseUsersattemptsInnerScored { 
    Attempts: Array<ModH5pactivityGetAttempts200ResponseUsersattemptsInnerScoredAttemptsInner>;
    /**
     * Grading method
     */
    Grademethod: string;
    /**
     * Scored attempts title
     */
    Title: string;
}

