/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModWorkshopGetSubmissions200ResponseSubmissionsInner } from './mod-workshop-get-submissions-200-response-submissions-inner';
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface ModWorkshopGetSubmissions200Response { 
    Submissions: Array<ModWorkshopGetSubmissions200ResponseSubmissionsInner>;
    /**
     * Total count of submissions.
     */
    Totalcount: number;
    /**
     * Total size (bytes) of the files attached to all the                     submissions (even the ones not returned due to pagination).
     */
    Totalfilesize: number;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

