/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * warning
 */
export interface ModAssignGetGrades200ResponseWarningsInner { 
    /**
     * item is always \'assignment\'
     */
    Item?: string;
    /**
     * when errorcode is 3 then itemid is an assignment id. When errorcode is 1, itemid is a course module id
     */
    Itemid?: number;
    /**
     * untranslated english message to explain the warning
     */
    Message?: string;
    /**
     * errorcode can be 3 (no grades found) or 1 (no permission to get grades)
     */
    Warningcode?: string;
}

