/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner } from './core-block-get-dashboard-blocks-200-response-blocks-inner-contents-files-inner';


/**
 * Glossaries
 */
export interface ModGlossaryGetGlossariesByCourses200ResponseGlossariesInner { 
    /**
     * If enabled, all participants with permission to create comments will be able to add comments to glossary entries
     */
    Allowcomments?: number;
    /**
     * If enabled, multiple entries can have the same concept name
     */
    Allowduplicatedentries?: number;
    /**
     * If enabled, students are provided with a link to a printer-friendly version of the glossary. The link is always available to teachers
     */
    Allowprintview?: number;
    /**
     * When approving glossary items you may wish to use a different display format
     */
    Approvaldisplayformat?: string;
    /**
     * Aggregate type
     */
    Assessed?: number;
    /**
     * Restrict rating to items created before this
     */
    Assesstimefinish?: number;
    /**
     * Restrict rating to items created after this
     */
    Assesstimestart?: number;
    Browsemodes?: Array<object>;
    /**
     * Whether the user can add a new entry
     */
    Canaddentry?: number;
    /**
     * Number of entries to complete
     */
    Completionentries?: number;
    /**
     * Course id
     */
    Course?: number;
    /**
     * Course module id
     */
    Coursemodule?: number;
    /**
     * If set to no, entries require approving by a teacher before they are viewable by everyone.
     */
    Defaultapproval?: number;
    /**
     * Display format type
     */
    Displayformat?: string;
    /**
     * Always allow editing
     */
    Editalways?: number;
    /**
     * Entries shown per page
     */
    Entbypage?: number;
    Globalglossary?: number;
    /**
     * Group id
     */
    Groupingid?: number;
    /**
     * Group mode
     */
    Groupmode?: number;
    /**
     * Activity instance id
     */
    Id?: number;
    /**
     * Activity introduction
     */
    Intro?: string;
    Introfiles?: Array<CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>;
    /**
     * intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Introformat?: number;
    /**
     * Forced activity language
     */
    Lang?: string;
    /**
     * If enabled this glossary is a main glossary.
     */
    Mainglossary?: number;
    /**
     * Activity name
     */
    Name?: string;
    /**
     * This setting specifies the number of glossary entry concepts to include in the RSS feed. Between 5 and 20 generally acceptable
     */
    Rssarticles?: number;
    /**
     * To enable the RSS feed for this activity, select either concepts with author or concepts without author to be included in the feed
     */
    Rsstype?: number;
    /**
     * Scale ID
     */
    Scale?: number;
    /**
     * Course section id
     */
    Section?: number;
    /**
     * If enabled, participants can browse all entries at once
     */
    Showall?: number;
    /**
     * If enabled, participants can browse the glossary by letters of the alphabet
     */
    Showalphabet?: number;
    /**
     * If enabled, participants can browse the glossary by special characters, such as @ and #
     */
    Showspecial?: number;
    /**
     * Time created
     */
    Timecreated?: number;
    /**
     * Time modified
     */
    Timemodified?: number;
    /**
     * If site-wide glossary auto-linking has been enabled by an administrator and this checkbox is ticked, the entry will be automatically linked wherever the concept words and phrases appear throughout the rest of the course.
     */
    Usedynalink?: number;
    /**
     * Visible
     */
    Visible?: boolean;
}

