/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The question page attempts
 */
export interface ModLessonGetQuestionsAttempts200ResponseAttemptsInner { 
    /**
     * The attempt answerid
     */
    Answerid?: number;
    /**
     * If it was the correct answer
     */
    Correct?: number;
    /**
     * The attempt id
     */
    Id?: number;
    /**
     * The attempt lessonid
     */
    Lessonid?: number;
    /**
     * The attempt pageid
     */
    Pageid?: number;
    /**
     * The lesson attempt number
     */
    Retry?: number;
    /**
     * The time the question was seen
     */
    Timeseen?: number;
    /**
     * The complete user answer
     */
    Useranswer?: string;
    /**
     * The user who did the attempt
     */
    Userid?: number;
}

