/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModForumSetLockState200ResponseTimes } from './mod-forum-set-lock-state-200-response-times';


export interface ModForumSetLockState200Response { 
    /**
     * The discussion we are locking.
     */
    Id: number;
    /**
     * The locked state of the discussion.
     */
    Locked: boolean;
    Times: ModForumSetLockState200ResponseTimes;
}

