/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner } from './core-block-get-dashboard-blocks-200-response-blocks-inner-contents-files-inner';


/**
 * Choices
 */
export interface ModChoiceGetChoicesByCourses200ResponseChoicesInner { 
    /**
     * Allow multiple choices
     */
    Allowmultiple?: boolean;
    /**
     * Allow update
     */
    Allowupdate?: boolean;
    /**
     * Completion on user submission
     */
    Completionsubmit?: boolean;
    /**
     * Course id
     */
    Course?: number;
    /**
     * Course module id
     */
    Coursemodule?: number;
    /**
     * Display mode (vertical, horizontal)
     */
    Display?: number;
    /**
     * Group id
     */
    Groupingid?: number;
    /**
     * Group mode
     */
    Groupmode?: number;
    /**
     * Activity instance id
     */
    Id?: number;
    /**
     * Include inactive users
     */
    Includeinactive?: boolean;
    /**
     * Activity introduction
     */
    Intro?: string;
    Introfiles?: Array<CoreBlockGetDashboardBlocks200ResponseBlocksInnerContentsFilesInner>;
    /**
     * intro format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Introformat?: number;
    /**
     * Forced activity language
     */
    Lang?: string;
    /**
     * Limit unswers
     */
    Limitanswers?: boolean;
    /**
     * Activity name
     */
    Name?: string;
    /**
     * If choice is published
     */
    Publish?: boolean;
    /**
     * Course section id
     */
    Section?: number;
    /**
     * Show available spaces
     */
    Showavailable?: boolean;
    /**
     * Show preview before timeopen
     */
    Showpreview?: boolean;
    /**
     * 0 never, 1 after answer, 2 after close, 3 always
     */
    Showresults?: number;
    /**
     * Show users who not answered yet
     */
    Showunanswered?: boolean;
    /**
     * Date of closing validity
     */
    Timeclose?: number;
    /**
     * Time of last modification
     */
    Timemodified?: number;
    /**
     * Date of opening validity
     */
    Timeopen?: number;
    /**
     * Visible
     */
    Visible?: boolean;
}

