/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner } from './core-blog-get-entries-200-response-entries-inner-summaryfiles-inner';


export interface ModWorkshopGetSubmissions200ResponseSubmissionsInner { 
    /**
     * Used by File API file_postupdate_standard_filemanager.
     */
    Attachment?: number;
    Attachmentfiles?: Array<CoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner>;
    /**
     * The author of the submission.
     */
    Authorid?: number;
    /**
     * Submission text.
     */
    Content?: string;
    Contentfiles?: Array<CoreBlogGetEntries200ResponseEntriesInnerSummaryfilesInner>;
    /**
     * content format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Contentformat?: number;
    /**
     * The trust mode of the data.
     */
    Contenttrust?: number;
    /**
     * Is this submission an example from teacher.
     */
    Example?: boolean;
    /**
     * Teacher comment/feedback for the author of the submission, for example describing the reasons                     for the grade overriding.
     */
    Feedbackauthor?: string;
    /**
     * feedbackauthor format (1 = HTML, 0 = MOODLE, 2 = PLAIN, or 4 = MARKDOWN)
     */
    Feedbackauthorformat?: number;
    /**
     * Aggregated grade for the submission. The grade is a decimal number from interval 0..100.                     If NULL then the grade for submission has not been aggregated yet.
     */
    Grade?: number;
    /**
     * Grade for the submission manually overridden by a teacher. Grade is always from interval 0..100.                     If NULL then the grade is not overriden.
     */
    Gradeover?: number;
    /**
     * The id of the user who has overridden the grade for submission.
     */
    Gradeoverby?: number;
    /**
     * The primary key of the record.
     */
    Id?: number;
    /**
     * Has this submission been submitted after the deadline or during the assessment phase?
     */
    Late?: number;
    /**
     * Shall the submission be available to other when the workshop is closed.
     */
    Published?: boolean;
    /**
     * Timestamp when the work was submitted for the first time.
     */
    Timecreated?: number;
    /**
     * The timestamp when grade or gradeover was recently modified.
     */
    Timegraded?: number;
    /**
     * Timestamp when the submission has been updated.
     */
    Timemodified?: number;
    /**
     * The submission title.
     */
    Title?: string;
    /**
     * The id of the workshop instance.
     */
    Workshopid?: number;
}

