/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModChoiceGetChoiceOptions200ResponseOptionsInner { 
    /**
     * we already answered
     */
    Checked?: boolean;
    /**
     * number of answers
     */
    Countanswers?: number;
    /**
     * option disabled
     */
    Disabled?: boolean;
    /**
     * true for orizontal, otherwise vertical
     */
    Displaylayout?: boolean;
    /**
     * option id
     */
    Id?: number;
    /**
     * maximum number of answers
     */
    Maxanswers?: number;
    /**
     * text of the choice
     */
    Text?: string;
}

