/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModFeedbackProcessPageRequestResponsesInner } from './mod-feedback-process-page-request-responses-inner';


export interface ModFeedbackProcessPageRequest { 
    /**
     * Course where user completes the feedback (for site feedbacks only).
     */
    Courseid?: number;
    /**
     * Feedback instance id.
     */
    Feedbackid: number;
    /**
     * Whether we want to jump to previous page.
     */
    Goprevious?: boolean;
    /**
     * The page being processed.
     */
    Page: number;
    Responses?: Array<ModFeedbackProcessPageRequestResponsesInner>;
}

