/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModH5pactivityGetUserAttempts200ResponseUsersattemptsInner } from './mod-h5pactivity-get-user-attempts-200-response-usersattempts-inner';
import { AuthEmailSignupUser200ResponseWarningsInner } from './auth-email-signup-user-200-response-warnings-inner';


export interface ModH5pactivityGetUserAttempts200Response { 
    /**
     * Activity course module ID
     */
    Activityid: number;
    Usersattempts: Array<ModH5pactivityGetUserAttempts200ResponseUsersattemptsInner>;
    Warnings?: Array<AuthEmailSignupUser200ResponseWarningsInner>;
}

