/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModForumGetDiscussionPost200ResponsePostTagsInnerUrls } from './mod-forum-get-discussion-post-200-response-post-tags-inner-urls';


export interface ModForumGetDiscussionPost200ResponsePostTagsInner { 
    /**
     * The display name of the tag
     */
    Displayname?: string;
    /**
     * Wehther this tag is flagged
     */
    Flag?: boolean;
    /**
     * The ID of the Tag
     */
    Id?: number;
    /**
     * Whether this is a standard tag
     */
    Isstandard?: boolean;
    /**
     * The tagid
     */
    Tagid?: number;
    Urls?: ModForumGetDiscussionPost200ResponsePostTagsInnerUrls;
}

