/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModDataGetFields200ResponseFieldsInner { 
    /**
     * The field type of the content.
     */
    Dataid?: number;
    /**
     * The field description.
     */
    Description?: string;
    /**
     * Field id.
     */
    Id?: number;
    /**
     * The field name.
     */
    Name?: string;
    /**
     * Field parameters
     */
    Param1?: string;
    /**
     * Field parameters
     */
    Param2?: string;
    /**
     * Field parameters
     */
    Param3?: string;
    /**
     * Field parameters
     */
    Param4?: string;
    /**
     * Field parameters
     */
    Param5?: string;
    /**
     * Field parameters
     */
    Param6?: string;
    /**
     * Field parameters
     */
    Param7?: string;
    /**
     * Field parameters
     */
    Param8?: string;
    /**
     * Field parameters
     */
    Param9?: string;
    /**
     * Field parameters
     */
    Param10?: string;
    /**
     * Whether is a field required or not.
     */
    Required?: boolean;
    /**
     * The field type.
     */
    Type?: string;
}

