/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModFeedbackGetPageItemsRequest { 
    /**
     * Course where user completes the feedback (for site feedbacks only).
     */
    Courseid?: number;
    /**
     * Feedback instance id
     */
    Feedbackid: number;
    /**
     * The page to get starting by 0
     */
    Page: number;
}

