/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModForumSetSubscriptionState200ResponseTimed } from './mod-forum-set-subscription-state-200-response-timed';
import { ModForumSetSubscriptionState200ResponseTimes } from './mod-forum-set-subscription-state-200-response-times';
import { ModForumSetSubscriptionState200ResponseCapabilities } from './mod-forum-set-subscription-state-200-response-capabilities';
import { ModForumSetSubscriptionState200ResponseUrls } from './mod-forum-set-subscription-state-200-response-urls';
import { ModForumSetSubscriptionState200ResponseUserstate } from './mod-forum-set-subscription-state-200-response-userstate';
import { ModForumSetSubscriptionState200ResponseGroup } from './mod-forum-set-subscription-state-200-response-group';


export interface ModForumSetSubscriptionState200Response { 
    Capabilities: ModForumSetSubscriptionState200ResponseCapabilities;
    /**
     * firstpostid
     */
    Firstpostid: number;
    /**
     * forumid
     */
    Forumid: number;
    Group?: ModForumSetSubscriptionState200ResponseGroup;
    /**
     * id
     */
    Id: number;
    /**
     * istimelocked
     */
    Istimelocked: boolean;
    /**
     * locked
     */
    Locked: boolean;
    /**
     * name
     */
    Name: string;
    /**
     * pinned
     */
    Pinned: boolean;
    Timed: ModForumSetSubscriptionState200ResponseTimed;
    Times: ModForumSetSubscriptionState200ResponseTimes;
    Urls: ModForumSetSubscriptionState200ResponseUrls;
    Userstate: ModForumSetSubscriptionState200ResponseUserstate;
}

