/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReportCompetencyDataForReport200ResponseUsercompetenciesInner } from './report-competency-data-for-report-200-response-usercompetencies-inner';
import { CoreCompetencyGradeCompetency200ResponseActionuser } from './core-competency-grade-competency-200-response-actionuser';
import { CoreCalendarGetActionEventsByCourses200ResponseGroupedbycourseInnerEventsInnerCourse } from './core-calendar-get-action-events-by-courses-200-response-groupedbycourse-inner-events-inner-course';


export interface ReportCompetencyDataForReport200Response { 
    Course: CoreCalendarGetActionEventsByCourses200ResponseGroupedbycourseInnerEventsInnerCourse;
    /**
     * Course id
     */
    Courseid: number;
    /**
     * True if rating is push to user plans
     */
    Pushratingstouserplans: boolean;
    User: CoreCompetencyGradeCompetency200ResponseActionuser;
    Usercompetencies: Array<ReportCompetencyDataForReport200ResponseUsercompetenciesInner>;
}

