/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ToolMoodlenetSearchCourses200ResponseCoursesInner { 
    /**
     * Category name
     */
    Coursecategory?: string;
    /**
     * course image
     */
    Courseimage?: string;
    /**
     * course full name
     */
    Fullname?: string;
    /**
     * is the course visible
     */
    Hidden?: number;
    /**
     * course id
     */
    Id?: number;
    /**
     * Next step of import
     */
    Viewurl?: string;
}

