/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolLpDataForUserEvidenceListPage200ResponseEvidenceInner } from './tool-lp-data-for-user-evidence-list-page-200-response-evidence-inner';


export interface ToolLpDataForUserEvidenceListPage200Response { 
    /**
     * Can the current user manage the user\'s evidence
     */
    Canmanage: boolean;
    Evidence: Array<ToolLpDataForUserEvidenceListPage200ResponseEvidenceInner>;
    Navigation: Array<object>;
    /**
     * Url to the tool_lp plugin folder on this Moodle site
     */
    Pluginbaseurl: string;
    /**
     * The user ID
     */
    Userid: number;
}

