/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCompetencyDuplicateCompetencyFramework200Response } from './core-competency-duplicate-competency-framework-200-response';


export interface ToolLpDataForCompetenciesManagePage200Response { 
    /**
     * True if this user has permission to manage competency frameworks
     */
    Canmanage: boolean;
    Framework: CoreCompetencyDuplicateCompetencyFramework200Response;
    /**
     * Context id for the framework
     */
    Pagecontextid: number;
    /**
     * Plugin base url
     */
    Pluginbaseurl: string;
    /**
     * JSON encoded data for rules
     */
    Rulesmodules: string;
    /**
     * Current search string
     */
    Search: string;
}

