/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner } from './core-course-get-enrolled-courses-by-timeline-classification-200-response-courses-inner';
import { ToolLpDataForCompetencySummary200ResponseComppath } from './tool-lp-data-for-competency-summary-200-response-comppath';
import { CoreCompetencyCreateCompetency200Response } from './core-competency-create-competency-200-response';
import { CoreCompetencyDuplicateCompetencyFramework200Response } from './core-competency-duplicate-competency-framework-200-response';
import { CoreCompetencyReadUserEvidence200ResponseCompetenciesInner } from './core-competency-read-user-evidence-200-response-competencies-inner';


export interface ToolLpDataForCompetencySummary200Response { 
    Competency: CoreCompetencyCreateCompetency200Response;
    Comppath: ToolLpDataForCompetencySummary200ResponseComppath;
    Framework: CoreCompetencyDuplicateCompetencyFramework200Response;
    /**
     * hascourses
     */
    Hascourses: boolean;
    /**
     * hasrelatedcompetencies
     */
    Hasrelatedcompetencies: boolean;
    Linkedcourses: Array<CoreCourseGetEnrolledCoursesByTimelineClassification200ResponseCoursesInner>;
    /**
     * pluginbaseurl
     */
    Pluginbaseurl: string;
    Relatedcompetencies: Array<CoreCompetencyReadUserEvidence200ResponseCompetenciesInner>;
    /**
     * scaleconfiguration
     */
    Scaleconfiguration: string;
    /**
     * scaleid
     */
    Scaleid: number;
    /**
     * taxonomyterm
     */
    Taxonomyterm: string;
}

