/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CoreCompetencyCreateTemplate200Response } from './core-competency-create-template-200-response';
import { ToolLpDataForTemplateCompetenciesPage200ResponseCompetenciesInner } from './tool-lp-data-for-template-competencies-page-200-response-competencies-inner';
import { ToolLpDataForTemplateCompetenciesPage200ResponseStatistics } from './tool-lp-data-for-template-competencies-page-200-response-statistics';


export interface ToolLpDataForTemplateCompetenciesPage200Response { 
    /**
     * User can manage competency frameworks
     */
    Canmanagecompetencyframeworks: boolean;
    /**
     * User can manage learning plan templates
     */
    Canmanagetemplatecompetencies: boolean;
    Competencies: Array<ToolLpDataForTemplateCompetenciesPage200ResponseCompetenciesInner>;
    /**
     * Url to the manage competencies page.
     */
    Manageurl: string;
    /**
     * Context ID
     */
    Pagecontextid: number;
    /**
     * Base URL of the plugin.
     */
    Pluginbaseurl: string;
    Statistics: ToolLpDataForTemplateCompetenciesPage200ResponseStatistics;
    Template: CoreCompetencyCreateTemplate200Response;
}

