/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInner } from './tool-lp-data-for-course-competencies-page-200-response-competencies-inner';
import { ToolLpDataForCourseCompetenciesPage200ResponseSettings } from './tool-lp-data-for-course-competencies-page-200-response-settings';
import { ToolLpDataForCourseCompetenciesPage200ResponseStatistics } from './tool-lp-data-for-course-competencies-page-200-response-statistics';


export interface ToolLpDataForCourseCompetenciesPage200Response { 
    /**
     * User can configure course competency settings
     */
    Canconfigurecoursecompetencies: boolean;
    /**
     * User can grade competencies.
     */
    Cangradecompetencies: boolean;
    /**
     * User can manage competency frameworks
     */
    Canmanagecompetencyframeworks: boolean;
    /**
     * User can manage linked course competencies
     */
    Canmanagecoursecompetencies: boolean;
    Competencies: Array<ToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInner>;
    /**
     * The current course id
     */
    Courseid: number;
    /**
     * Current user id, if the user is a gradable user.
     */
    Gradableuserid?: number;
    /**
     * Url to the manage competencies page.
     */
    Manageurl: string;
    /**
     * The current page context ID.
     */
    Pagecontextid: number;
    /**
     * Url to the course competencies page.
     */
    Pluginbaseurl: string;
    Settings: ToolLpDataForCourseCompetenciesPage200ResponseSettings;
    Statistics: ToolLpDataForCourseCompetenciesPage200ResponseStatistics;
}

