/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolLpDataForCompetencyFrameworksManagePage200ResponseCompetencyframeworksInner } from './tool-lp-data-for-competency-frameworks-manage-page-200-response-competencyframeworks-inner';


export interface ToolLpDataForCompetencyFrameworksManagePage200Response { 
    Competencyframeworks: Array<ToolLpDataForCompetencyFrameworksManagePage200ResponseCompetencyframeworksInner>;
    Navigation: Array<object>;
    /**
     * The page context id
     */
    Pagecontextid: number;
    /**
     * Url to the tool_lp plugin folder on this Moodle site
     */
    Pluginbaseurl: string;
}

