/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ToolLpDataForCompetencySummary200Response } from './tool-lp-data-for-competency-summary-200-response';
import { ToolLpDataForUserCompetencySummary200ResponseUsercompetency } from './tool-lp-data-for-user-competency-summary-200-response-usercompetency';
import { ToolLpDataForUserCompetencySummary200ResponseEvidenceInner } from './tool-lp-data-for-user-competency-summary-200-response-evidence-inner';
import { ToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse } from './tool-lp-data-for-course-competencies-page-200-response-competencies-inner-usercompetencycourse';
import { CoreCompetencyGradeCompetency200ResponseActionuser } from './core-competency-grade-competency-200-response-actionuser';
import { ToolLpDataForUserCompetencySummary200ResponseUsercompetencyplan } from './tool-lp-data-for-user-competency-summary-200-response-usercompetencyplan';
import { CoreCompetencyReadPlan200ResponseCommentarea } from './core-competency-read-plan-200-response-commentarea';


export interface ToolLpDataForUserCompetencySummaryInCourse200ResponseUsercompetencysummary { 
    /**
     * cangrade
     */
    Cangrade: boolean;
    Commentarea?: CoreCompetencyReadPlan200ResponseCommentarea;
    Competency: ToolLpDataForCompetencySummary200Response;
    Evidence: Array<ToolLpDataForUserCompetencySummary200ResponseEvidenceInner>;
    /**
     * showrelatedcompetencies
     */
    Showrelatedcompetencies: boolean;
    User: CoreCompetencyGradeCompetency200ResponseActionuser;
    Usercompetency?: ToolLpDataForUserCompetencySummary200ResponseUsercompetency;
    Usercompetencycourse?: ToolLpDataForCourseCompetenciesPage200ResponseCompetenciesInnerUsercompetencycourse;
    Usercompetencyplan?: ToolLpDataForUserCompetencySummary200ResponseUsercompetencyplan;
}

