export * from './auth-email.service';
import { AuthEmailService } from './auth-email.service';
export * from './block-accessreview.service';
import { BlockAccessreviewService } from './block-accessreview.service';
export * from './block-iomad-company-admin.service';
import { BlockIomadCompanyAdminService } from './block-iomad-company-admin.service';
export * from './block-recentlyaccesseditems.service';
import { BlockRecentlyaccesseditemsService } from './block-recentlyaccesseditems.service';
export * from './block-starredcourses.service';
import { BlockStarredcoursesService } from './block-starredcourses.service';
export * from './enrol-guest.service';
import { EnrolGuestService } from './enrol-guest.service';
export * from './enrol-license.service';
import { EnrolLicenseService } from './enrol-license.service';
export * from './enrol-manual.service';
import { EnrolManualService } from './enrol-manual.service';
export * from './enrol-meta.service';
import { EnrolMetaService } from './enrol-meta.service';
export * from './enrol-self.service';
import { EnrolSelfService } from './enrol-self.service';
export * from './gradereport-grader.service';
import { GradereportGraderService } from './gradereport-grader.service';
export * from './gradereport-overview.service';
import { GradereportOverviewService } from './gradereport-overview.service';
export * from './gradereport-singleview.service';
import { GradereportSingleviewService } from './gradereport-singleview.service';
export * from './gradereport-user.service';
import { GradereportUserService } from './gradereport-user.service';
export * from './gradingform-guide.service';
import { GradingformGuideService } from './gradingform-guide.service';
export * from './gradingform-rubric.service';
import { GradingformRubricService } from './gradingform-rubric.service';
export * from './local-iomad-learningpath.service';
import { LocalIomadLearningpathService } from './local-iomad-learningpath.service';
export * from './media-videojs.service';
import { MediaVideojsService } from './media-videojs.service';
export * from './message-airnotifier.service';
import { MessageAirnotifierService } from './message-airnotifier.service';
export * from './message-popup.service';
import { MessagePopupService } from './message-popup.service';
export * from './mod-assign.service';
import { ModAssignService } from './mod-assign.service';
export * from './mod-bigbluebuttonbn.service';
import { ModBigbluebuttonbnService } from './mod-bigbluebuttonbn.service';
export * from './mod-book.service';
import { ModBookService } from './mod-book.service';
export * from './mod-chat.service';
import { ModChatService } from './mod-chat.service';
export * from './mod-choice.service';
import { ModChoiceService } from './mod-choice.service';
export * from './mod-data.service';
import { ModDataService } from './mod-data.service';
export * from './mod-feedback.service';
import { ModFeedbackService } from './mod-feedback.service';
export * from './mod-folder.service';
import { ModFolderService } from './mod-folder.service';
export * from './mod-forum.service';
import { ModForumService } from './mod-forum.service';
export * from './mod-glossary.service';
import { ModGlossaryService } from './mod-glossary.service';
export * from './mod-h5pactivity.service';
import { ModH5pactivityService } from './mod-h5pactivity.service';
export * from './mod-imscp.service';
import { ModImscpService } from './mod-imscp.service';
export * from './mod-iomadcertificate.service';
import { ModIomadcertificateService } from './mod-iomadcertificate.service';
export * from './mod-label.service';
import { ModLabelService } from './mod-label.service';
export * from './mod-lesson.service';
import { ModLessonService } from './mod-lesson.service';
export * from './mod-lti.service';
import { ModLtiService } from './mod-lti.service';
export * from './mod-page.service';
import { ModPageService } from './mod-page.service';
export * from './mod-quiz.service';
import { ModQuizService } from './mod-quiz.service';
export * from './mod-resource.service';
import { ModResourceService } from './mod-resource.service';
export * from './mod-scorm.service';
import { ModScormService } from './mod-scorm.service';
export * from './mod-survey.service';
import { ModSurveyService } from './mod-survey.service';
export * from './mod-url.service';
import { ModUrlService } from './mod-url.service';
export * from './mod-wiki.service';
import { ModWikiService } from './mod-wiki.service';
export * from './mod-workshop.service';
import { ModWorkshopService } from './mod-workshop.service';
export * from './moodle.service';
import { MoodleService } from './moodle.service';
export * from './paygw-paypal.service';
import { PaygwPaypalService } from './paygw-paypal.service';
export * from './qbank-columnsortorder.service';
import { QbankColumnsortorderService } from './qbank-columnsortorder.service';
export * from './qbank-editquestion.service';
import { QbankEditquestionService } from './qbank-editquestion.service';
export * from './qbank-tagquestion.service';
import { QbankTagquestionService } from './qbank-tagquestion.service';
export * from './qbank-viewquestiontext.service';
import { QbankViewquestiontextService } from './qbank-viewquestiontext.service';
export * from './quizaccess-seb.service';
import { QuizaccessSebService } from './quizaccess-seb.service';
export * from './report-competency.service';
import { ReportCompetencyService } from './report-competency.service';
export * from './report-insights.service';
import { ReportInsightsService } from './report-insights.service';
export * from './tiny-autosave.service';
import { TinyAutosaveService } from './tiny-autosave.service';
export * from './tiny-equation.service';
import { TinyEquationService } from './tiny-equation.service';
export * from './tiny-premium.service';
import { TinyPremiumService } from './tiny-premium.service';
export * from './tool-analytics.service';
import { ToolAnalyticsService } from './tool-analytics.service';
export * from './tool-behat.service';
import { ToolBehatService } from './tool-behat.service';
export * from './tool-dataprivacy.service';
import { ToolDataprivacyService } from './tool-dataprivacy.service';
export * from './tool-iomadpolicy.service';
import { ToolIomadpolicyService } from './tool-iomadpolicy.service';
export * from './tool-lp.service';
import { ToolLpService } from './tool-lp.service';
export * from './tool-mobile.service';
import { ToolMobileService } from './tool-mobile.service';
export * from './tool-moodlenet.service';
import { ToolMoodlenetService } from './tool-moodlenet.service';
export * from './tool-policy.service';
import { ToolPolicyService } from './tool-policy.service';
export * from './tool-templatelibrary.service';
import { ToolTemplatelibraryService } from './tool-templatelibrary.service';
export * from './tool-usertours.service';
import { ToolUsertoursService } from './tool-usertours.service';
export * from './tool-xmldb.service';
import { ToolXmldbService } from './tool-xmldb.service';
export const APIS = [AuthEmailService, BlockAccessreviewService, BlockIomadCompanyAdminService, BlockRecentlyaccesseditemsService, BlockStarredcoursesService, EnrolGuestService, EnrolLicenseService, EnrolManualService, EnrolMetaService, EnrolSelfService, GradereportGraderService, GradereportOverviewService, GradereportSingleviewService, GradereportUserService, GradingformGuideService, GradingformRubricService, LocalIomadLearningpathService, MediaVideojsService, MessageAirnotifierService, MessagePopupService, ModAssignService, ModBigbluebuttonbnService, ModBookService, ModChatService, ModChoiceService, ModDataService, ModFeedbackService, ModFolderService, ModForumService, ModGlossaryService, ModH5pactivityService, ModImscpService, ModIomadcertificateService, ModLabelService, ModLessonService, ModLtiService, ModPageService, ModQuizService, ModResourceService, ModScormService, ModSurveyService, ModUrlService, ModWikiService, ModWorkshopService, MoodleService, PaygwPaypalService, QbankColumnsortorderService, QbankEditquestionService, QbankTagquestionService, QbankViewquestiontextService, QuizaccessSebService, ReportCompetencyService, ReportInsightsService, TinyAutosaveService, TinyEquationService, TinyPremiumService, ToolAnalyticsService, ToolBehatService, ToolDataprivacyService, ToolIomadpolicyService, ToolLpService, ToolMobileService, ToolMoodlenetService, ToolPolicyService, ToolTemplatelibraryService, ToolUsertoursService, ToolXmldbService];
