/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable } from 'rxjs';
import { EnrolGuestGetInstanceInfo200Response } from '../model/enrol-guest-get-instance-info-200-response';
import { EnrolGuestGetInstanceInfoRequest } from '../model/enrol-guest-get-instance-info-request';
import { EnrolGuestValidatePassword200Response } from '../model/enrol-guest-validate-password-200-response';
import { EnrolGuestValidatePasswordRequest } from '../model/enrol-guest-validate-password-request';
import { ErrorResponse } from '../model/error-response';
import { Configuration } from '../configuration';


@Injectable()
export class EnrolGuestService {

    protected basePath = 'https://localhost/webservice/restful/server.php';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * Return guest enrolment instance information.
     * Return guest enrolment instance information.
     * @param enrolGuestGetInstanceInfoRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public enrolGuestGetInstanceInfo(enrolGuestGetInstanceInfoRequest: EnrolGuestGetInstanceInfoRequest, ): Observable<AxiosResponse<EnrolGuestGetInstanceInfo200Response>>;
    public enrolGuestGetInstanceInfo(enrolGuestGetInstanceInfoRequest: EnrolGuestGetInstanceInfoRequest, ): Observable<any> {

        if (enrolGuestGetInstanceInfoRequest === null || enrolGuestGetInstanceInfoRequest === undefined) {
            throw new Error('Required parameter enrolGuestGetInstanceInfoRequest was null or undefined when calling enrolGuestGetInstanceInfo.');
        }

        let headers = {...this.defaultHeaders};

        // authentication (apiKey) required
        if (this.configuration.apiKeys?.["Authorization"]) {
            headers['Authorization'] = this.configuration.apiKeys["Authorization"];
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return this.httpClient.post<EnrolGuestGetInstanceInfo200Response>(`${this.basePath}/enrol_guest_get_instance_info`,
            enrolGuestGetInstanceInfoRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers
            }
        );
    }
    /**
     * Perform password validation.
     * Perform password validation.
     * @param enrolGuestValidatePasswordRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public enrolGuestValidatePassword(enrolGuestValidatePasswordRequest: EnrolGuestValidatePasswordRequest, ): Observable<AxiosResponse<EnrolGuestValidatePassword200Response>>;
    public enrolGuestValidatePassword(enrolGuestValidatePasswordRequest: EnrolGuestValidatePasswordRequest, ): Observable<any> {

        if (enrolGuestValidatePasswordRequest === null || enrolGuestValidatePasswordRequest === undefined) {
            throw new Error('Required parameter enrolGuestValidatePasswordRequest was null or undefined when calling enrolGuestValidatePassword.');
        }

        let headers = {...this.defaultHeaders};

        // authentication (apiKey) required
        if (this.configuration.apiKeys?.["Authorization"]) {
            headers['Authorization'] = this.configuration.apiKeys["Authorization"];
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return this.httpClient.post<EnrolGuestValidatePassword200Response>(`${this.basePath}/enrol_guest_validate_password`,
            enrolGuestValidatePasswordRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers
            }
        );
    }
}
