/**
 * Moodle Webservice API
 * Auto-generated OpenAPI spec for Moodle\'s Webservice API. Requires installation of the Catalyst RESTful API plugin: https://github.com/catalyst/moodle-webservice_restful.
 *
 * The version of the OpenAPI document: 4.3.4
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@nestjs/common';
import { HttpService } from '@nestjs/axios';
import { AxiosResponse } from 'axios';
import { Observable } from 'rxjs';
import { ErrorResponse } from '../model/error-response';
import { ToolMoodlenetSearchCourses200Response } from '../model/tool-moodlenet-search-courses-200-response';
import { ToolMoodlenetSearchCoursesRequest } from '../model/tool-moodlenet-search-courses-request';
import { ToolMoodlenetVerifyWebfinger200Response } from '../model/tool-moodlenet-verify-webfinger-200-response';
import { ToolMoodlenetVerifyWebfingerRequest } from '../model/tool-moodlenet-verify-webfinger-request';
import { Configuration } from '../configuration';


@Injectable()
export class ToolMoodlenetService {

    protected basePath = 'https://localhost/webservice/restful/server.php';
    public defaultHeaders: Record<string,string> = {};
    public configuration = new Configuration();

    constructor(protected httpClient: HttpService, @Optional() configuration: Configuration) {
        this.configuration = configuration || this.configuration;
        this.basePath = configuration?.basePath || this.basePath;
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        return consumes.includes(form);
    }

    /**
     * For some given input search for a course that matches
     * For some given input search for a course that matches
     * @param toolMoodlenetSearchCoursesRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public toolMoodlenetSearchCourses(toolMoodlenetSearchCoursesRequest: ToolMoodlenetSearchCoursesRequest, ): Observable<AxiosResponse<ToolMoodlenetSearchCourses200Response>>;
    public toolMoodlenetSearchCourses(toolMoodlenetSearchCoursesRequest: ToolMoodlenetSearchCoursesRequest, ): Observable<any> {

        if (toolMoodlenetSearchCoursesRequest === null || toolMoodlenetSearchCoursesRequest === undefined) {
            throw new Error('Required parameter toolMoodlenetSearchCoursesRequest was null or undefined when calling toolMoodlenetSearchCourses.');
        }

        let headers = {...this.defaultHeaders};

        // authentication (apiKey) required
        if (this.configuration.apiKeys?.["Authorization"]) {
            headers['Authorization'] = this.configuration.apiKeys["Authorization"];
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return this.httpClient.post<ToolMoodlenetSearchCourses200Response>(`${this.basePath}/tool_moodlenet_search_courses`,
            toolMoodlenetSearchCoursesRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers
            }
        );
    }
    /**
     * Verify if the passed information resolves into a WebFinger profile URL
     * Verify if the passed information resolves into a WebFinger profile URL
     * @param toolMoodlenetVerifyWebfingerRequest 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public toolMoodlenetVerifyWebfinger(toolMoodlenetVerifyWebfingerRequest: ToolMoodlenetVerifyWebfingerRequest, ): Observable<AxiosResponse<ToolMoodlenetVerifyWebfinger200Response>>;
    public toolMoodlenetVerifyWebfinger(toolMoodlenetVerifyWebfingerRequest: ToolMoodlenetVerifyWebfingerRequest, ): Observable<any> {

        if (toolMoodlenetVerifyWebfingerRequest === null || toolMoodlenetVerifyWebfingerRequest === undefined) {
            throw new Error('Required parameter toolMoodlenetVerifyWebfingerRequest was null or undefined when calling toolMoodlenetVerifyWebfinger.');
        }

        let headers = {...this.defaultHeaders};

        // authentication (apiKey) required
        if (this.configuration.apiKeys?.["Authorization"]) {
            headers['Authorization'] = this.configuration.apiKeys["Authorization"];
        }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers['Accept'] = httpHeaderAcceptSelected;
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers['Content-Type'] = httpContentTypeSelected;
        }
        return this.httpClient.post<ToolMoodlenetVerifyWebfinger200Response>(`${this.basePath}/tool_moodlenet_verify_webfinger`,
            toolMoodlenetVerifyWebfingerRequest,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers
            }
        );
    }
}
